### ISSUE TITLE
Include element codename and external id to ElementModelBinder

### ISSUE THREAD

**Issue by Sevitas** [kontent-ai/management-sdk-net#210]
### Motivation

Element model provider binds value to element using element id. https://github.com/kontent-ai/management-sdk-net/blob/a94d1601fc2baa7aa43b5dcffc1bf835085bf01a/Kontent.Ai.Management/Modules/ModelBuilders/ElementModelProvider.cs#L21

### Proposed solution

Include codename and external id.

### Additional context

Blocks https://github.com/kontent-ai/model-generator-net/issues/167

**Comment by Sevitas** [comment]
After more detailed look, we have found out that MAPI returns only IDs, thus we won't be able to support externalId/codename by default. User will be obliged to provide their own custom ModelProvider. In this task please create just ExternalId attribute

**Comment by gormal** [comment]
I do not think it's a good idea to merge this PR. As I understand it there were no customer complaints/feature requests for this feature and it adds complexity to the SDK, not to mention that the customer needs to implement his/her model provider anyway. Honestly, I would suggest abandoning this issue for now and keeping the SDK as simple as possible.

What do you say @Simply007?

**Comment by Simply007** [comment]
I agree that extending the ModelProvider is not necessary.

But including the attribute definition is beneficial, because than users can use this information and work with it in the project.

I would create `KontentElementExtenalIdAttibute` like we have in [KontentElementIdAttribute](https://github.com/kontent-ai/management-sdk-net/blob/4f208f31681af26aab5a24dcc734815f4a5587e3/Kontent.Ai.Management/Modules/ModelBuilders/KontentElementIdAttribute.cs#L9) and then maybe include extension method `GatsContentElementExterneld` extension method similar as [GetKontentElementId](https://github.com/kontent-ai/management-sdk-net/blob/4f208f31681af26aab5a24dcc734815f4a5587e3/Kontent.Ai.Management/Modules/Extensions/PropertyInfoExtensions.cs#LL15C24-L15C43).

Maybe we can also add `GetKontentElementCodeName` extension method to have it complete.

**Comment by Simply007** [comment]
The code of the `GetContentElementExternald ` is currently in https://github.com/kontent-ai/management-sdk-net/pull/212/files#diff-013c3d43481817e94ec4b06f36a06f660be5d6c2bc51a726d953ad43e4611c88R27

**Comment by Sevitas** [comment]
I am not sure if it is beneficial to introduce those methods/attributes. MAPI's response model contains just the ID. I think it might be a good idea to abandon this feature for now.

**Comment by Simply007** [comment]
I agree - I didn't realize that the MAPI does not response with the external IDs identification.

We might add the alternative of [GetKontentElementId](https://github.com/kontent-ai/management-sdk-net/blob/master/Kontent.Ai.Management/Modules/Extensions/PropertyInfoExtensions.cs) - `GetKontentElementCodeName`.

 I think that is the smallest addition we can add to make the codename loading easy to get.
 
 What do you think @gormal, @Sevitas?
