### ISSUE TITLE
Possible NullReferenceException

### ISSUE THREAD

**Issue by zdenekjurka** [kontent-ai/management-sdk-net#211]
### Brief bug description

NullReferenceException was thrown from multiple ManagementClient methods.

### Repro steps

Exception is thrown from "ManagementHttpClient" when call to "_httpClient.SendAsync" in "SendHttpMessage" throws an exception (in my case it was timeout exception), this exception is captured by used retry policy ("ManagementHttpClient" 
 line 62 "_resiliencePolicyProvider.Policy.ExecuteAndCaptureAsync" ) as result of this there is null assigned to response variable on line 65. This than causes exception on line 73 "if (response.IsSuccessStatusCode)".

Also please note that built in retry policy is not handling any exceptions thrown from HttpClient (there could be many transient exceptions related to network communication).

### Expected behavior

I would expect ManagementException in this case.

**Comment by gormal** [comment]
Improve overall default retry policy. It only worked for responses from MAPI, but it did not take into account that an exception can be thrown. Please, be aware, this is a breaking change because  `ManagamentException` is thrown instead of `HttpRequestException`. So some exception handling in a customer codebase might stop working. 

I would prefer to release this as a major version.

**Comment by gormal** [comment]
"ManagementException" is intended solely for error responses from MAPI. To maintain this, I removed the section where "HttpRequestException" was wrapped within "ManagementException." As a result, this is no longer considered a breaking change.
